# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='slug'),
        ),
    ]
