# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161028_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblock',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='postblock',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='block',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='text', verbose_name='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(default='html', verbose_name='body html'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostBlock',
        ),
    ]
