# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161109_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('write_post', 'Write post'),), 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
