# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161109_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_html',
            field=models.TextField(blank=True, verbose_name='description html'),
        ),
    ]
