# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 10:57
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to),
        ),
    ]
