# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default='', verbose_name='preview'),
        ),
    ]
