# Generated by Django 3.1.3 on 2020-11-09 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import timezone_field.fields
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to)),
                ('background', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to)),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='status')),
                ('about', models.TextField(blank=True, verbose_name='about me')),
                ('followers_counter', models.PositiveIntegerField(default=0, verbose_name='followers counter')),
                ('subscriptions_counter', models.PositiveIntegerField(default=0, verbose_name='subscriptions counter')),
                ('blogs_counter', models.PositiveIntegerField(default=0, verbose_name='blogs counter')),
                ('clubs_counter', models.PositiveIntegerField(default=0, verbose_name='clubs counter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
