# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blogs_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='subscriptions counter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='clubs_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='clubs counter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='followers counter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='subscriptions counter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to),
        ),
    ]
