# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20161014_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blogs_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='blogs counter'),
        ),
    ]
